"""add owner_id foreign key to shortenedurl

Revision ID: 1652ea96f718
Revises: 95ac15733486
Create Date: 2026-04-28 14:08:52.866735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1652ea96f718'
down_revision: Union[str, Sequence[str], None] = '95ac15733486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortenedurl', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shortenedurl', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shortenedurl', type_='foreignkey')
    op.drop_column('shortenedurl', 'owner_id')
    # ### end Alembic commands ###
