"""Add nanoid code to ShortenedURL

Revision ID: 3dff54e3512c
Revises: 61d9efc12fd8
Create Date: 2026-03-10 20:26:39.618764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3dff54e3512c'
down_revision: Union[str, Sequence[str], None] = '61d9efc12fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortenedurl', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False))
    op.create_index(op.f('ix_shortenedurl_code'), 'shortenedurl', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortenedurl_code'), table_name='shortenedurl')
    op.drop_column('shortenedurl', 'code')
    # ### end Alembic commands ###
