"""Add expired_at to shortenedurl

Revision ID: f5e7e5582f97
Revises: 1652ea96f718
Create Date: 2026-05-14 16:23:13.988093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f5e7e5582f97'
down_revision: Union[str, Sequence[str], None] = '1652ea96f718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortenedurl', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortenedurl', 'expires_at')
    # ### end Alembic commands ###
